version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    cooldown:
      default-days: 3

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    cooldown:
      default-days: 3
    # Group packages into shared PR
    groups:
      bootstrap:
        patterns:
          - 'bootstrap'
      sortablejs:
        patterns:
          - 'sortablejs'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    cooldown:
      default-days: 3