version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    # Group packages into shared PR
    groups:
      bootstrap:
        patterns:
          - 'bootstrap'
      sortablejs:
        patterns:
          - 'sortablejs'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily